// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBdb0x80EgvjLqKD6rjUoTKdW2WOSEgFRM',
    appId: '1:948986142226:web:d38a4d4313644a377c02cb',
    messagingSenderId: '948986142226',
    projectId: 'agrisage-b60eb',
    authDomain: 'agrisage-b60eb.firebaseapp.com',
    storageBucket: 'agrisage-b60eb.firebasestorage.app',
    measurementId: 'G-KJJ9YFK3XG',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyD_r3SSPotXPiuk-SZ34LQifEkRfmNdlHg',
    appId: '1:948986142226:android:47ad12395fbb34207c02cb',
    messagingSenderId: '948986142226',
    projectId: 'agrisage-b60eb',
    storageBucket: 'agrisage-b60eb.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCVm44okJoHbt28EnAXCsMARHSrAyemW_k',
    appId: '1:948986142226:ios:bcf93f11d627f8777c02cb',
    messagingSenderId: '948986142226',
    projectId: 'agrisage-b60eb',
    storageBucket: 'agrisage-b60eb.firebasestorage.app',
    iosClientId: '948986142226-s4bnmg5ra9u1399obkat9ruko53iui2r.apps.googleusercontent.com',
    iosBundleId: 'com.example.agrisage',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyCVm44okJoHbt28EnAXCsMARHSrAyemW_k',
    appId: '1:948986142226:ios:bcf93f11d627f8777c02cb',
    messagingSenderId: '948986142226',
    projectId: 'agrisage-b60eb',
    storageBucket: 'agrisage-b60eb.firebasestorage.app',
    iosClientId: '948986142226-s4bnmg5ra9u1399obkat9ruko53iui2r.apps.googleusercontent.com',
    iosBundleId: 'com.example.agrisage',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyBdb0x80EgvjLqKD6rjUoTKdW2WOSEgFRM',
    appId: '1:948986142226:web:62af2b025f581ab97c02cb',
    messagingSenderId: '948986142226',
    projectId: 'agrisage-b60eb',
    authDomain: 'agrisage-b60eb.firebaseapp.com',
    storageBucket: 'agrisage-b60eb.firebasestorage.app',
    measurementId: 'G-3KK56GSG7B',
  );

}